steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/qwiklabs-gcp-03-6d8a45ad3bba/sample/httpd-app:latest', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/qwiklabs-gcp-03-6d8a45ad3bba/sample/httpd-app:latest']
options:
  logging: 'CLOUD_LOGGING_ONLY'

